import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { ReactQueryProvider } from './ReactQueryProvider'
import { HandleProductContextProvider } from '@/context/HandleProductContext'
import { SkeletonTheme } from 'react-loading-skeleton'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={montserrat.className}>
          <HandleProductContextProvider>
            <SkeletonTheme baseColor="#1D2330" highlightColor="#252C3A">
              {children}
            </SkeletonTheme>
          </HandleProductContextProvider>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
